apiVersion: 1

datasources:
  - name: ngsi-api
    type: yesoreyeram-infinity-datasource
    access: proxy
    isDefault: true
    url: http://ngsi-api:3000
    uid: "ngsi-api-infinity"
    jsonData:
      base_url: http://ngsi-api:3000
      datasource_mode: "basic"
    editable: true
