apiVersion: 1

datasources:
  - name: ngsi-api
    type: yesoreyeram-infinity-datasource
    access: proxy
    isDefault: true
    jsonData:
      allowedHosts:
        - "ngsi-api:3000"
      # optional convenience default; panels can still set full URL
      url: "http://ngsi-api:3000"
